"""initial

Revision ID: 301b7949e972
Revises: 
Create Date: 2025-06-16 13:29:36.554668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '301b7949e972'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('businesses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('business_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('whatsapp_number', sa.VARCHAR(), nullable=True),
    sa.Column('waba_status', sa.VARCHAR(), nullable=True),
    sa.Column('whatsapp_sender_sid', sa.VARCHAR(), nullable=True),
    sa.Column('whatsapp_sender_id', sa.VARCHAR(), nullable=True),
    sa.Column('waba_id', sa.VARCHAR(), nullable=True),
    sa.Column('whatsapp_status', sa.VARCHAR(), nullable=True),
    sa.Column('whatsapp_profile', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ### 