"""add reset tokens table

Revision ID: add_reset_tokens_table
Revises: add_cancelled_at_column
Create Date: 2024-12-19 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_reset_tokens_table'
down_revision = 'add_cancelled_at_column'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reset_token_business_expires', 'reset_tokens', ['business_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_reset_tokens_business_id'), 'reset_tokens', ['business_id'], unique=False)
    op.create_index(op.f('ix_reset_tokens_token'), 'reset_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_tokens_token'), table_name='reset_tokens')
    op.drop_index(op.f('ix_reset_tokens_business_id'), table_name='reset_tokens')
    op.drop_index('idx_reset_token_business_expires', table_name='reset_tokens')
    op.drop_table('reset_tokens')
    # ### end Alembic commands ### 