"use client"

// =========================================================================
// LanguageContext — WDB adapter for the ported SupportAI agent-chat module.
//
// The shared render module (components/agent-chat/*, components/ui/ai-chat-input,
// components/chat-charts/*) resolves all user-facing labels through
// `useLanguage().t(key)` (+ `.language` for locale formatting). WDB is German-
// primary, so we ship the exact German strings SupportAI uses for the referenced
// namespaces: agentChatCore.*, agentChatBlocks.*, uiDecorative.chatInput.*,
// general.*. Some keys are built via template literals in the block components,
// so the FULL DE subtrees are included (not just literal call sites).
//
// `t()` is a flat lookup with key-fallback (identical semantics to SupportAI):
// unknown keys return the key itself. Interpolation placeholders like {count}
// or {fields} are returned verbatim — the consuming components do their own
// String.replace(), exactly as in SupportAI.
//
// No React Provider is required: `useLanguage()` returns a stable module-level
// object, so the ported components work anywhere in the WDB tree unchanged.
//
// Generiert aus Support AI/src/contexts/LanguageContext.tsx (deutscher Block).
// =========================================================================

const DE: Record<string, string> = {
    'general.cancel': 'Abbrechen',
    'general.delete': 'Löschen',
    'general.loading': 'Laden...',
    'agentChatCore.quickActions.config.label': 'Konfiguration',
    'agentChatCore.quickActions.config.description': 'Aktive Einstellungen',
    'agentChatCore.quickActions.config.prompt': 'Zeig mir die aktive Verhaltenskonfiguration des Mail-Assistenten.',
    'agentChatCore.quickActions.analyze.label': 'Logs analysieren',
    'agentChatCore.quickActions.analyze.description': 'Verbesserungen finden',
    'agentChatCore.quickActions.analyze.prompt': 'Analysiere die letzten Process Logs und gib mir Verbesserungsvorschläge für die Verhaltenskonfiguration.',
    'agentChatCore.quickActions.kpis.label': 'KPIs abrufen',
    'agentChatCore.quickActions.kpis.description': 'Aktuelle Metriken abrufen',
    'agentChatCore.quickActions.kpis.prompt': 'Zeig mir die aktuellen Dashboard-KPIs und Support-KPIs.',
    'agentChatCore.quickActions.searchLogs.label': 'Logs suchen',
    'agentChatCore.quickActions.searchLogs.description': 'Process Logs durchsuchen',
    'agentChatCore.quickActions.searchLogs.prompt': 'Suche in den Process Logs nach: ',
    'agentChatCore.quickActions.trends.label': 'Trendthemen',
    'agentChatCore.quickActions.trends.description': 'Aktuelle Themen',
    'agentChatCore.quickActions.trends.prompt': 'Zeig mir die aktuellen Trendthemen-Kategorien.',
    'agentChatCore.quickActions.chatbot.label': 'Chatbot-Config',
    'agentChatCore.quickActions.chatbot.description': 'Website-Chatbot Einstellungen',
    'agentChatCore.quickActions.chatbot.prompt': 'Zeig mir die aktive Chatbot-Konfiguration.',
    'agentChatCore.quickActions.kbAgent.label': 'KB-Agent fragen',
    'agentChatCore.quickActions.kbAgent.description': 'KB-Agent befragen',
    'agentChatCore.quickActions.kbAgent.prompt': 'Frage den Wissensdatenbank-Agenten: ',
    'agentChatCore.placeholder.default': 'Support AI Agent...',
    'agentChatCore.placeholder.config': 'Zeig mir die Konfiguration...',
    'agentChatCore.placeholder.analyze': 'Analysiere die letzten Logs...',
    'agentChatCore.placeholder.kpis': 'KPIs abrufen...',
    'agentChatCore.placeholder.trends': 'Trendthemen anzeigen...',
    'agentChatCore.newChat': 'Neuer Chat',
    'agentChatCore.history': 'Chat-Verlauf',
    'agentChatCore.greeting.prefix': 'Wie kann ich',
    'agentChatCore.greeting.highlight': 'helfen',
    'agentChatCore.greeting.subtitle': 'Frag mich nach KPIs, Auswertungen, Konfigurationen oder lass mich Logs analysieren.',
    'agentChatCore.tableContext.rowsSingular': 'Zeile',
    'agentChatCore.tableContext.rowsPlural': 'Zeilen',
    'agentChatCore.tableContext.defaultTitle': 'Tabelle',
    'agentChatCore.editMessage': 'Nachricht bearbeiten',
    'agentChatCore.resend': 'Neu senden',
    'agentChatCore.screenshotFallback': 'Screenshot',
    'agentChatCore.trace.working': 'Agent arbeitet',
    'agentChatCore.trace.error': 'Trace · Fehler aufgetreten',
    'agentChatCore.trace.stepsSingular': 'Trace · {count} Schritt',
    'agentChatCore.trace.stepsPlural': 'Trace · {count} Schritte',
    'agentChatCore.trace.thinking': 'Agent überlegt',
    'agentChatCore.trace.workSteps': 'Arbeitsschritte',
    'agentChatCore.trace.answerFallback': 'Antwort',
    'agentChatCore.trace.errorLabel': 'Fehler:',
    'agentChatCore.trace.orchestrator': 'Orchestrator',
    'agentChatCore.history.empty': 'Noch keine Chats',
    'agentChatCore.history.untitled': 'Chat',
    'agentChatCore.rename': 'Umbenennen',
    'agentChatCore.delete.confirmTitle': 'Wirklich löschen',
    'agentChatCore.delete.confirmAriaLabel': 'Löschen bestätigen',
    'agentChatCore.delete.cancelAriaLabel': 'Löschen abbrechen',
    'agentChatCore.confirmation.confirmedLabel': 'Plan ausführen bestätigt',
    'agentChatCore.confirmation.cancelledLabel': 'Plan abgebrochen',
    'agentChatCore.insight.title': 'Erkenntnis umsetzen',
    'agentChatCore.insight.effort': 'Aufwand:',
    'agentChatCore.insight.typeKb': 'Wissensdatenbank',
    'agentChatCore.insight.typeTool': 'Tool',
    'agentChatCore.insight.typeRule': 'Sonderfall-Regel',
    'agentChatCore.insight.typeRouting': 'Routing',
    'agentChatCore.insight.collapseAria': 'Briefing einklappen',
    'agentChatCore.insight.expandAria': 'Briefing ausklappen',
    'agentChatCore.processLog.attached': 'Process Log angehängt',
    'agentChatCore.processLog.collapseAria': 'Vollkontext einklappen',
    'agentChatCore.processLog.expandAria': 'Vollkontext ausklappen',
    'agentChatCore.processLog.loading': 'Lade vollständiges Log…',
    'agentChatCore.processLog.sectionMail': 'Kundenmail',
    'agentChatCore.processLog.sectionQuestions': 'Extrahierte Fragen',
    'agentChatCore.processLog.sectionAnswer': 'Antwort',
    'agentChatCore.processLog.sectionReasoning': 'Begründung',
    'agentChatCore.processLog.sectionTools': 'Tools & Skills',
    'agentChatCore.processLog.openInDashboard': 'Im Mail-Dashboard öffnen',
    'agentChatCore.quote.open': '„',
    'agentChatCore.quote.close': '“',
    'agentChatCore.choice.maxSelectionsErrorSingular': 'Maximal {max} Auswahl möglich.',
    'agentChatCore.choice.maxSelectionsErrorPlural': 'Maximal {max} Auswahlen möglich.',
    'agentChatCore.form.missingFieldsError': 'Bitte ausfüllen: {fields}',
    'uiDecorative.chatInput.typeMessage': 'Nachricht eingeben...',
    'uiDecorative.chatInput.attachImage': 'Bild anhängen',
    'uiDecorative.chatInput.stop': 'Stoppen',
    'uiDecorative.chatInput.stopRun': 'Lauf stoppen',
    'uiDecorative.chatInput.send': 'Senden',
    'uiDecorative.chatInput.searchWeb': 'Im Web suchen...',
    'uiDecorative.chatInput.thinkDeeply': 'Tiefgehend nachdenken...',
    'uiDecorative.chatInput.searchToggleLabel': 'Suche',
    'uiDecorative.chatInput.enableWebSearch': 'Web-Suche aktivieren',
    'uiDecorative.chatInput.thinkToggleLabel': 'Denken',
    'uiDecorative.chatInput.deepThinking': 'Tiefes Nachdenken (GPT 5.4)',
    'uiDecorative.chatInput.stopRecording': 'Aufnahme stoppen',
    'uiDecorative.chatInput.voiceInput': 'Spracheingabe',
    'agentChatBlocks.common.actionLabel': 'Aktion',
    'agentChatBlocks.common.executionFailed': 'Ausführung fehlgeschlagen',
    'agentChatBlocks.common.actionSucceeded': 'Aktion erfolgreich ausgeführt.',
    'agentChatBlocks.common.actionExecuted': 'Aktion ausgeführt.',
    'agentChatBlocks.common.unknownError': 'Unbekannter Fehler',
    'agentChatBlocks.code.defaultTitle': 'Code',
    'agentChatBlocks.confirmation.stepFallback': 'Schritt',
    'agentChatBlocks.confirmation.alreadyExecuted': 'Bereits ausgeführt.',
    'agentChatBlocks.confirmation.alreadyCancelled': 'Bereits abgebrochen.',
    'agentChatBlocks.confirmation.planCancelled': 'Plan abgebrochen.',
    'agentChatBlocks.confirmation.planExecutedSeeHistory': 'Plan ausgeführt — Ergebnis siehe Verlauf unten.',
    'agentChatBlocks.confirmation.confirmDefaultLabel': 'Bestätigen',
    'agentChatBlocks.confirmation.decisionDefaultPrefix': 'Entscheidung',
    'agentChatBlocks.confirmation.actionInFlight': 'Aktion läuft bereits.',
    'agentChatBlocks.confirmation.planRunningInChat': 'Plan wird im Chat ausgeführt…',
    'agentChatBlocks.confirmation.planCancelling': 'Plan wird abgebrochen…',
    'agentChatBlocks.confirmation.agentKnowledgeManagement': 'KB-Management',
    'agentChatBlocks.confirmation.agentMail': 'Mail-Agent',
    'agentChatBlocks.confirmation.agentWebsite': 'Website-Agent',
    'agentChatBlocks.confirmation.agentPhone': 'Telefon-Agent',
    'agentChatBlocks.confirmation.agentInternal': 'Interner-Agent',
    'agentChatBlocks.confirmation.agentDashboard': 'Dashboard-Agent',
    'agentChatBlocks.confirmation.agentFollowUp': 'Follow-Up-Agent',
    'agentChatBlocks.confirmation.agentTask': 'Task-Agent',
    'agentChatBlocks.confirmation.agentToolBuilder': 'Tool-Builder',
    'agentChatBlocks.confirmation.agentTrend': 'Trend-Agent',
    'agentChatBlocks.confirmation.agentAccount': 'Account-Agent',
    'agentChatBlocks.confirmation.agentMemory': 'Memory-Agent',
    'agentChatBlocks.confirmation.agentPlanner': 'Planer-Agent',
    'agentChatBlocks.confirmation.agentAnalytics': 'Analytics-Agent',
    'agentChatBlocks.confirmation.auditUndoLabel': 'Änderung rückgängig',
    'agentChatBlocks.confirmation.actionAlreadyExecutedDedup': 'Aktion war bereits ausgeführt — kein erneutes Anlegen.',
    'agentChatBlocks.confirmation.statusFailed': '{label} — fehlgeschlagen',
    'agentChatBlocks.confirmation.statusInFlight': '{label} — läuft bereits',
    'agentChatBlocks.confirmation.statusRunning': '{label} — wird ausgeführt…',
    'agentChatBlocks.confirmation.statusDone': '{label} — erledigt',
    'agentChatBlocks.confirmation.statusCancelledChoice': '{label} gewählt',
    'agentChatBlocks.form.submitDefaultLabel': 'Absenden',
    'agentChatBlocks.form.defaultPrefix': 'Formular',
    'agentChatBlocks.form.selectPlaceholder': 'Bitte wählen …',
    'agentChatBlocks.form.requiredFieldsSingular': '{count} Pflichtfeld',
    'agentChatBlocks.form.requiredFieldsPlural': '{count} Pflichtfelder',
    'agentChatBlocks.form.allFieldsOptional': 'Alle Felder optional',
    'agentChatBlocks.choices.submitMultiLabel': 'Auswahl senden',
    'agentChatBlocks.choices.submitEitherOrLabel': 'Entscheidung senden',
    'agentChatBlocks.choices.submitSingleLabel': 'Option senden',
    'agentChatBlocks.choices.minSelectionsErrorSingular': 'Bitte mindestens {min} Option wählen.',
    'agentChatBlocks.choices.minSelectionsErrorPlural': 'Bitte mindestens {min} Optionen wählen.',
    'agentChatBlocks.choices.defaultPrefix': 'Auswahl',
    'agentChatBlocks.choices.selectionSummary': '{count} gewählt · min {min}, max {max}',
    'agentChatBlocks.choices.oneSelected': '1 Auswahl gesetzt',
    'agentChatBlocks.choices.pleaseSelectOne': 'Bitte eine Option wählen',
    'agentChatBlocks.table.defaultTitle': 'Daten',
    'agentChatBlocks.table.attachRowsSingular': '{count} Zeile anhängen',
    'agentChatBlocks.table.attachRowsPlural': '{count} Zeilen anhängen',
    'agentChatBlocks.table.entriesCount': '{count} Einträge',
    'agentChatBlocks.table.showLess': 'Weniger anzeigen',
    'agentChatBlocks.table.showMoreRows': '+{count} weitere Zeilen',
    'agentChatBlocks.statusCard.open': 'Offen',
    'agentChatBlocks.statusCard.inProgress': 'Läuft …',
    'agentChatBlocks.statusCard.resolved': 'Gelöst',
    'agentChatBlocks.statusCard.closed': 'Geschlossen',
    'agentChatBlocks.statusCard.escalated': 'Eskaliert',
    'agentChatBlocks.statusCard.updatedAtLabel': 'Aktualisiert:',
    'agentChatCore.quickActions.weekly.label': 'Wochenreport',
    'agentChatCore.quickActions.weekly.prompt': 'Erstelle einen Wochenreport mit KPIs, Trends und Diagrammen.',
    'agentChatCore.quickActions.weekly.description': 'KPIs & Trends der Woche',
    'agentChatCore.quickActions.kpisDashboard.label': 'Dashboard KPIs',
    'agentChatCore.quickActions.kpisDashboard.prompt': 'Zeig mir die aktuellen Dashboard-KPIs und Support-KPIs mit Diagrammen.',
    'agentChatCore.quickActions.analyzeDashboard.prompt': 'Analysiere die letzten Process Logs und gib mir Verbesserungsvorschläge.',
    'agentChatCore.quickActions.kbAgentDashboard.label': 'Wissensdatenbank',
    'agentChatCore.placeholderDashboard.weekly': 'Wie lief die letzte Woche?',
    'agentChatCore.placeholderDashboard.kpis': 'Zeig mir die aktuellen KPIs...',
    'agentChatCore.placeholderDashboard.analyze': 'Analysiere die Process Logs...',
    'agentChatCore.placeholderDashboard.trends': 'Welche Trendthemen gibt es?',
    'agentChatCore.placeholderDashboard.config': 'Chatbot konfigurieren...',
    'agentChatCore.greeting.subtitleDashboard': 'Frag mich nach KPIs, Auswertungen, Konfigurationen oder lass mich Logs analysieren. Ich kann dir alles als Diagramm aufbereiten.',
    'agentChatCore.tableContext.attachedDataHeader': 'Angehängte Tabellendaten ({title})',
    'agentChatCore.tableContext.selected': 'ausgewählt',
    'agentChatCore.textSelection.promptPrefix': 'Bezogen auf diesen Abschnitt:',
    'agentChatCore.imageOnlyFallbackPrompt': 'Schau dir bitte dieses Bild an.',
}

// Sprachcode-Union wie in SupportAI. Einige geteilte Komponenten
// (ConversationList, chat-charts) lesen `language` für Locale-Formatierung
// (z. B. `language === "de" ? "de-DE" : …`). WDB ist deutschsprachig-primär.
type Language = "de" | "en" | "es"

type LanguageContextValue = {
  t: (key: string) => string
  language: Language
}

const value: LanguageContextValue = {
  t: (key: string): string => DE[key] ?? key,
  language: "de",
}

export function useLanguage(): LanguageContextValue {
  return value
}
